name: production_strict
description: Strict security policy for production containers

rules:
  - name: max_risk_score
    type: max_risk_score
    value: 25
    severity: critical
    description: Production containers must have low risk score
    
  - name: no_privileged
    type: forbidden_capability
    value: ['SYS_ADMIN', 'SYS_MODULE', 'SYS_RAWIO', 'NET_ADMIN', 'SYS_PTRACE']
    severity: critical
    description: No dangerous capabilities in production
    
  - name: non_root_required
    type: required_user
    value: non-root
    severity: critical
    description: Production containers MUST run as non-root
    
  - name: no_critical_vulns
    type: max_vulnerabilities
    severity: critical
    value: 0
    description: Zero critical vulnerabilities in production
    
  - name: minimal_high_vulns
    type: max_vulnerabilities
    severity: high
    value: 2
    description: Maximum 2 high severity vulnerabilities
    
  - name: resource_limits
    type: required_limits
    value:
      memory: true
      cpu: true
    severity: medium
    description: Resource limits must be set

enforcement: block  # Immediately stop non-compliant containers

exceptions: []  # No exceptions in production