# Hyper-NixOS Master Configuration
# Version: 1.0.0
# 
# This is the complete configuration including all features and modules.
# Customize by editing the options below or using the setup wizard.
# 
# For help: Run 'hv help' or see /etc/hypervisor/docs/

{ config, lib, pkgs, ... }:

{
  imports = [
    # Hardware configuration (generated by nixos-generate-config)
    ./hardware-configuration.nix
    
    # Core system modules
    ./modules/core/base.nix
    ./modules/core/directories.nix
    ./modules/core/keymap-sanitizer.nix
    ./modules/core/portable-base.nix
    ./modules/core/optimized-system.nix
    
    # Feature management system
    ./modules/features/feature-categories.nix
    ./modules/features/feature-manager.nix
    ./modules/features/adaptive-docs.nix
    ./modules/features/educational-content.nix
    
    # Security modules
    ./modules/security/profiles.nix
    ./modules/security/privilege-separation.nix
    ./modules/security/polkit-rules.nix
    ./modules/security/threat-detection.nix
    ./modules/security/threat-response.nix
    ./modules/security/threat-intelligence.nix
    ./modules/security/behavioral-analysis.nix
    
    # Virtualization modules
    ./modules/virtualization/libvirt.nix
    ./modules/virtualization/qemu.nix
    
    # Networking modules
    ./modules/networking/base.nix
    ./modules/networking/bridges.nix
    
    # Service modules
    ./modules/services/ssh.nix
    ./modules/services/monitoring.nix
    
    # User feature selections (generated by setup wizard)
    # Uncomment after running: hv setup
    # ./hypervisor-features.nix
  ];

  # System identification
  networking.hostName = "hyper-nixos";
  system.stateVersion = "24.05";  # Don't change this after installation
  
  # Boot configuration
  boot = {
    loader = {
      systemd-boot.enable = true;
      efi.canTouchEfiVariables = true;
      timeout = 3;
    };
    
    # Kernel optimizations for virtualization
    kernelParams = [ 
      "intel_iommu=on"  # or "amd_iommu=on" for AMD
      "iommu=pt"
      "kvm_intel.nested=1"  # or "kvm_amd.nested=1" for AMD
      "transparent_hugepage=madvise"
    ];
    
    # Required kernel modules
    kernelModules = [ 
      "kvm-intel"  # or "kvm-amd" for AMD
      "vfio"
      "vfio_iommu_type1"
      "vfio_pci"
    ];
    
    # Early kernel modules
    initrd.kernelModules = [ "vfio_pci" ];
  };
  
  # Hypervisor configuration
  hypervisor = {
    # Core features (always enabled)
    enable = true;
    
    # Feature management
    featureManager = {
      enable = true;
      profile = "balanced";  # Options: minimal, balanced, full, custom
      riskTolerance = "balanced";  # Options: paranoid, cautious, balanced, accepting
      generateReport = true;
      
      # For custom profile, specify features:
      # enabledFeatures = [ "webDashboard" "monitoring" "backup" ];
    };
    
    # Documentation and education
    documentation = {
      enable = true;
      profile = "intermediate";  # Options: beginner, intermediate, expert
      verbosity = "medium";  # Options: minimal, low, medium, high
      enableHints = true;
      enableTutorials = true;
      contextAware = true;
    };
    
    education = {
      enable = true;
      defaultLevel = "intermediate";
      enableInteractiveTutorials = true;
      enableProgressTracking = true;
    };
    
    # Security configuration
    security = {
      # Privilege separation
      privileges = {
        enable = true;
        allowPasswordlessVMOperations = true;
        
        # Define users by role (customize these)
        vmUsers = [ ];  # Basic VM operations
        vmOperators = [ ];  # Advanced VM operations
        systemAdmins = [ ];  # System administration
      };
      
      # Polkit rules
      polkit = {
        enable = true;
        enableVMRules = true;
        enableOperatorRules = true;
      };
      
      # Threat detection
      threatDetection = {
        enable = true;
        detectionMode = "active";  # Options: passive, active, aggressive
        enableMachineLearning = true;
        enableBehavioralAnalysis = true;
        enableThreatIntelligence = true;
        enableAutomatedResponse = false;  # Set to true for automatic responses
        
        sensors = {
          network = true;
          system = true;
          files = true;
          memory = true;
          virtualization = true;
        };
        
        alerting = {
          channels = [ "syslog" ];  # Add: email, slack, webhook
          thresholds = {
            info = 100;
            medium = 20;
            high = 5;
          };
        };
      };
      
      # Threat response
      threatResponse = {
        enable = true;
        mode = "interactive";  # Options: monitor, interactive, automatic
        enabledPlaybooks = [
          "networkIsolation"
          "authProtection"
          "resourceProtection"
        ];
        forensics.enable = true;
      };
      
      # Behavioral analysis
      behavioralAnalysis = {
        enable = true;
        modelUpdateInterval = "daily";
        zeroDayDetection = {
          enable = true;
          confidenceThreshold = 70;
        };
      };
      
      # Threat intelligence
      threatIntelligence = {
        enable = true;
        enabledFeeds = [
          "emergingThreats"
          "malwareDomains"
          "malwareBazaar"
        ];
        updateInterval = "6h";
        enableCorrelation = true;
      };
    };
    
    # Default VM configuration
    defaults = {
      vcpus = 2;
      memory = 2048;  # MB
      diskSize = "20G";
      networkBridge = "virbr0";
    };
  };
  
  # Virtualization settings
  virtualisation = {
    libvirtd = {
      enable = true;
      qemu = {
        package = pkgs.qemu_kvm;
        runAsRoot = false;
        swtpm.enable = true;
        ovmf = {
          enable = true;
          packages = [ pkgs.OVMFFull.fd ];
        };
      };
      
      # Allow regular users to manage VMs
      extraConfig = ''
        unix_sock_group = "libvirtd"
        unix_sock_ro_perms = "0777"
        unix_sock_rw_perms = "0770"
        auth_unix_ro = "none"
        auth_unix_rw = "none"
      '';
    };
    
    # Container support (optional)
    podman = {
      enable = false;  # Enable if needed
      dockerCompat = true;
    };
  };
  
  # Network configuration
  networking = {
    # Enable firewall
    firewall = {
      enable = true;
      trustedInterfaces = [ "virbr0" ];
      
      # Allow VM traffic
      allowedTCPPorts = [ ];  # Add ports as needed
      allowedUDPPorts = [ ];
    };
    
    # Network bridges for VMs
    bridges = {
      "virbr0" = {
        interfaces = [ ];  # Leave empty for NAT
      };
      # Add more bridges as needed:
      # "br0" = {
      #   interfaces = [ "eno1" ];  # Bridge to physical interface
      # };
    };
    
    # Enable NAT for default bridge
    nat = {
      enable = true;
      internalInterfaces = [ "virbr0" ];
      externalInterface = null;  # Auto-detect
    };
  };
  
  # System packages
  environment.systemPackages = with pkgs; [
    # Virtualization tools
    virt-manager
    virt-viewer
    libguestfs-with-appliance
    
    # System tools
    vim
    git
    tmux
    htop
    iotop
    ncdu
    tree
    
    # Network tools
    bridge-utils
    tcpdump
    nmap
    
    # Security tools
    aide
    rkhunter
    
    # Monitoring tools
    prometheus
    grafana
    loki
    
    # Our custom tools
    (import ./packages/hypervisor-cli.nix { inherit pkgs; })
  ];
  
  # System services
  services = {
    # SSH access
    openssh = {
      enable = true;
      settings = {
        PasswordAuthentication = false;
        PermitRootLogin = "no";
        X11Forwarding = false;
      };
    };
    
    # Time synchronization
    chrony.enable = true;
    
    # System monitoring (if monitoring feature enabled)
    prometheus = lib.mkIf (elem "monitoring" config.hypervisor.featureManager.enabledFeatures) {
      enable = true;
      port = 9090;
      
      exporters = {
        node = {
          enable = true;
          enabledCollectors = [ "systemd" "processes" "filesystem" "netdev" ];
        };
      };
      
      scrapeConfigs = [
        {
          job_name = "node";
          static_configs = [{
            targets = [ "localhost:9100" ];
          }];
        }
      ];
    };
    
    # Grafana (if monitoring feature enabled)
    grafana = lib.mkIf (elem "monitoring" config.hypervisor.featureManager.enabledFeatures) {
      enable = true;
      settings = {
        server = {
          http_port = 3000;
          http_addr = "127.0.0.1";
        };
      };
    };
  };
  
  # User configuration
  users = {
    # Don't allow mutable users
    mutableUsers = false;
    
    # Define your users here
    users = {
      # Example admin user (customize or remove)
      admin = {
        isNormalUser = true;
        description = "System Administrator";
        extraGroups = [ "wheel" "libvirtd" "kvm" ];
        # Set password hash with: mkpasswd -m sha-512
        hashedPassword = "$6$rounds=100000$...";  # CHANGE THIS!
        openssh.authorizedKeys.keys = [
          # Add your SSH public key here
        ];
      };
    };
  };
  
  # System activation scripts
  system.activationScripts = {
    hypervisorSetup = ''
      # Create required directories
      mkdir -p /etc/hypervisor/{features,reports,docs,certs}
      mkdir -p /var/lib/hypervisor/{vms,backups,logs,threats,ml-models}
      
      # Set permissions
      chmod 750 /etc/hypervisor
      chmod 755 /var/lib/hypervisor
      
      # First-run check
      if [ ! -f /etc/hypervisor/.setup-complete ]; then
        cat <<EOF > /etc/motd.first-run
╔═══════════════════════════════════════════════════════════════╗
║              Welcome to Hyper-NixOS!                          ║
╠═══════════════════════════════════════════════════════════════╣
║                                                               ║
║  This appears to be your first run. Please:                  ║
║                                                               ║
║  1. Run the setup wizard:                                     ║
║     $ hv setup                                                ║
║                                                               ║
║  2. Configure users in /etc/nixos/configuration.nix          ║
║                                                               ║
║  3. Rebuild the system:                                       ║
║     $ sudo nixos-rebuild switch                               ║
║                                                               ║
║  For help: hv help                                            ║
║                                                               ║
╚═══════════════════════════════════════════════════════════════╝
EOF
      fi
    '';
  };
  
  # Message of the day
  environment.etc."motd".text = lib.mkDefault ''
    ╔═══════════════════════════════════════════════════════════════╗
    ║                    Hyper-NixOS v1.0.0                         ║
    ╠═══════════════════════════════════════════════════════════════╣
    ║                                                               ║
    ║  Quick Commands:                                              ║
    ║  • hv help       - Show help                                  ║
    ║  • hv vm         - VM management                              ║
    ║  • hv setup      - Configuration wizard                       ║
    ║  • hv security   - Security status                            ║
    ║  • hv monitor    - System monitoring                          ║
    ║                                                               ║
    ║  Documentation: /etc/hypervisor/docs/                         ║
    ║                                                               ║
    ╚═══════════════════════════════════════════════════════════════╝
  '';
  
  # Performance tuning
  powerManagement.cpuFreqGovernor = "performance";
  
  # Security hardening
  security = {
    # Enable audit framework
    audit.enable = true;
    auditd.enable = true;
    
    # AppArmor
    apparmor = {
      enable = true;
      killUnconfinedConfinables = false;
    };
    
    # Kernel hardening
    kernel.sysctl = {
      # Network hardening
      "net.ipv4.conf.all.log_martians" = 1;
      "net.ipv4.conf.default.log_martians" = 1;
      "net.ipv4.icmp_echo_ignore_broadcasts" = 1;
      "net.ipv4.conf.all.accept_source_route" = 0;
      "net.ipv6.conf.all.accept_source_route" = 0;
      
      # VM performance
      "vm.swappiness" = 10;
      "vm.dirty_ratio" = 10;
      "vm.dirty_background_ratio" = 5;
      
      # File limits
      "fs.file-max" = 2097152;
      "fs.inotify.max_user_watches" = 524288;
    };
  };
}

# Configuration Tips:
# 
# 1. First Run:
#    - Run 'hv setup' to configure features
#    - Add your users to the vmUsers/vmOperators/systemAdmins lists
#    - Set user passwords with hashedPassword
#    - Add SSH keys for remote access
# 
# 2. Hardware-Specific:
#    - For AMD CPUs: Change kvm-intel to kvm-amd
#    - For AMD CPUs: Change kvm_intel.nested to kvm_amd.nested
#    - Adjust hypervisor.defaults based on your hardware
# 
# 3. Network:
#    - Configure additional bridges in networking.bridges
#    - Adjust firewall rules as needed
#    - Set up VLANs if required
# 
# 4. Security:
#    - Review and adjust threat detection settings
#    - Configure alert channels (email, Slack, etc.)
#    - Set up automated responses carefully
# 
# 5. After Changes:
#    - Always run: sudo nixos-rebuild test
#    - If successful: sudo nixos-rebuild switch