{ config, pkgs, lib, ... }:

# Hyper-NixOS Main Configuration
# This is the top-level configuration file that imports all modules

{
  # ═══════════════════════════════════════════════════════════════
  # System Version
  # ═══════════════════════════════════════════════════════════════
  system.stateVersion = "24.05";
  
  # ═══════════════════════════════════════════════════════════════
  # TTY Auto-Login Configuration
  # ═══════════════════════════════════════════════════════════════
  # TTY autologin is now managed by modules/security/profiles.nix
  # - Headless profile: autologin as "hypervisor-operator"
  # - Management profile: autologin as configured management user
  
  # ═══════════════════════════════════════════════════════════════
  # Module Imports - Organized by Topic
  # ═══════════════════════════════════════════════════════════════
  imports = [
    # ─────────────────────────────────────────────────────────────
    # Hardware Configuration (generated by nixos-generate-config)
    # ─────────────────────────────────────────────────────────────
    ./hardware-configuration.nix
    
    # ─────────────────────────────────────────────────────────────
    # Core System Configuration
    # ─────────────────────────────────────────────────────────────
    ./modules/core/options.nix
    ./modules/core/boot.nix
    ./modules/core/system.nix
    ./modules/core/packages.nix
    ./modules/core/directories.nix
    ./modules/core/logrotate.nix
    ./modules/core/cache-optimization.nix
    
    # ─────────────────────────────────────────────────────────────
    # Network Configuration
    # ─────────────────────────────────────────────────────────────
    ./modules/network-settings/base.nix
    ./modules/network-settings/performance.nix
    ./modules/network-settings/security.nix
    ./modules/network-settings/firewall.nix
    ./modules/network-settings/ssh.nix
    ./modules/network-settings/isolation.nix
    
    # ─────────────────────────────────────────────────────────────
    # Security Configuration
    # ─────────────────────────────────────────────────────────────
    ./modules/security/base.nix
    ./modules/security/profiles.nix
    ./modules/security/kernel-hardening.nix
    ./modules/security/biometrics.nix
    
    # ─────────────────────────────────────────────────────────────
    # Virtualization Configuration
    # ─────────────────────────────────────────────────────────────
    ./modules/virtualization/libvirt.nix
    ./scripts/vfio-boot.nix
    
    # ─────────────────────────────────────────────────────────────
    # Monitoring Configuration
    # ─────────────────────────────────────────────────────────────
    ./modules/monitoring/prometheus.nix
    ./modules/monitoring/alerting.nix
    ./modules/monitoring/logging.nix
    
    # ─────────────────────────────────────────────────────────────
    # Automation Services
    # ─────────────────────────────────────────────────────────────
    ./modules/automation/services.nix
    ./modules/automation/backup.nix
    
    # ─────────────────────────────────────────────────────────────
    # GUI Configuration (optional)
    # ─────────────────────────────────────────────────────────────
    ./modules/gui/desktop.nix
    ./modules/gui/input.nix
    
    # ─────────────────────────────────────────────────────────────
    # Web Dashboard
    # ─────────────────────────────────────────────────────────────
    ./modules/web/dashboard.nix
    
    # ─────────────────────────────────────────────────────────────
    # VM Management
    # ─────────────────────────────────────────────────────────────
    ./modules/vm-management/resource-quotas.nix
    ./modules/vm-management/snapshots.nix
    ./modules/vm-management/scheduling.nix
    
    # ─────────────────────────────────────────────────────────────
    # Storage Management
    # ─────────────────────────────────────────────────────────────
    ./modules/storage-management/quotas.nix
    ./modules/storage-management/encryption.nix
    
  # ─────────────────────────────────────────────────────────────
  # Optional Modules (conditionally loaded)
  # ─────────────────────────────────────────────────────────────
  ] ++ lib.optional (builtins.pathExists ./modules/virtualization/performance.nix) 
      ./modules/virtualization/performance.nix
  
  # ─────────────────────────────────────────────────────────────
  # Local Override Configuration Files
  # These allow per-host customization without modifying the base
  # ─────────────────────────────────────────────────────────────
    ++ lib.optional (builtins.pathExists /var/lib/hypervisor/configuration/performance.nix) 
      /var/lib/hypervisor/configuration/performance.nix
    ++ lib.optional (builtins.pathExists /var/lib/hypervisor/configuration/perf-local.nix) 
      /var/lib/hypervisor/configuration/perf-local.nix
    ++ lib.optional (builtins.pathExists /var/lib/hypervisor/configuration/security-local.nix) 
      /var/lib/hypervisor/configuration/security-local.nix
    ++ lib.optional (builtins.pathExists /var/lib/hypervisor/configuration/users-local.nix) 
      /var/lib/hypervisor/configuration/users-local.nix
    ++ lib.optional (builtins.pathExists /var/lib/hypervisor/configuration/system-local.nix) 
      /var/lib/hypervisor/configuration/system-local.nix
    ++ lib.optional (builtins.pathExists /var/lib/hypervisor/configuration/management-local.nix) 
      /var/lib/hypervisor/configuration/management-local.nix
    ++ lib.optional (builtins.pathExists /var/lib/hypervisor/configuration/swap-local.nix) 
      /var/lib/hypervisor/configuration/swap-local.nix
    ++ lib.optional (builtins.pathExists /var/lib/hypervisor/configuration/gui-local.nix) 
      /var/lib/hypervisor/configuration/gui-local.nix
    
    # Note: Strict security is opt-in via /var/lib/hypervisor/configuration/security-strict.nix
    # Enable it by: echo '{ imports = [ /etc/hypervisor/modules/security/strict.nix ]; }' | sudo tee /var/lib/hypervisor/configuration/security-strict.nix
    ++ lib.optional (builtins.pathExists /var/lib/hypervisor/configuration/security-strict.nix) 
      /var/lib/hypervisor/configuration/security-strict.nix
    
    # Import last so it can override bad values from local overrides
    ++ [ ./modules/core/keymap-sanitizer.nix ];
  
  # ═══════════════════════════════════════════════════════════════
  # Systemd Services - Hypervisor Menu
  # ═══════════════════════════════════════════════════════════════
  systemd.services.hypervisor-menu = {
    description = "Boot-time Hypervisor VM Menu";
    wantedBy = lib.optional (config.hypervisor.menu.enableAtBoot && !config.hypervisor.gui.enableAtBoot) "multi-user.target";
    after = [ "network-online.target" "libvirtd.service" ];
    wants = [ "network-online.target" "libvirtd.service" ];
    
    # Avoid racing the Display Manager for VT1
    conflicts = [ "getty@tty1.service" "display-manager.service" ];
    
    # Base serviceConfig - can be overridden by security modules
    serviceConfig = lib.mkDefault {
      Type = "simple";
      ExecStart = "${pkgs.bash}/bin/bash /etc/hypervisor/scripts/menu.sh";
      WorkingDirectory = "/etc/hypervisor";
      User = "${config.hypervisor.management.userName}";
      SupplementaryGroups = [ "kvm" "libvirtd" "video" ];
      Restart = "always";
      RestartSec = 2;
      StateDirectory = "hypervisor";
      LogsDirectory = "";
      
      ExecStartPre = [
        "${pkgs.coreutils}/bin/mkdir -p /var/lib/hypervisor/logs"
        "${pkgs.coreutils}/bin/touch /var/lib/hypervisor/logs/menu.log"
      ];
      
      StandardInput = "tty";
      StandardOutput = "tty";
      TTYPath = "/dev/tty1";
      TTYReset = true;
      TTYVHangup = true;
      
      Environment = [
        "SDL_VIDEODRIVER=kmsdrm"
        "SDL_AUDIODRIVER=alsa"
        "DIALOG=whiptail"
        "TERM=linux"
        "PATH=/run/current-system/sw/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      ];
      
      # Security hardening
      NoNewPrivileges = true;
      PrivateTmp = true;
      ProtectSystem = "strict";
      ProtectHome = true;
      PrivateDevices = false;
      DeviceAllow = [ "/dev/kvm rw" "/dev/dri/* rw" ];
      LockPersonality = true;
      MemoryDenyWriteExecute = true;
      RestrictAddressFamilies = [ "AF_UNIX" "AF_INET" "AF_INET6" ];
      SystemCallFilter = [ "@system-service" "@pkey" "@chown" ];
      ProtectKernelTunables = true;
      ProtectKernelModules = true;
      ProtectControlGroups = true;
      RestrictNamespaces = true;
      RestrictSUIDSGID = true;
      CapabilityBoundingSet = "";
      AmbientCapabilities = "";
    };
  };
  
  # ═══════════════════════════════════════════════════════════════
  # Systemd Services - First Boot Welcome
  # ═══════════════════════════════════════════════════════════════
  systemd.services.hypervisor-first-boot-welcome = {
    description = "First-boot Welcome Screen";
    wantedBy = lib.optional config.hypervisor.firstBootWelcome.enableAtBoot "multi-user.target";
    after = [ "network-online.target" "systemd-tmpfiles-setup.service" ];
    before = [ "hypervisor-menu.service" ];
    wants = [ "network-online.target" ];
    conflicts = [ "getty@tty1.service" ];
    
    serviceConfig = {
      Type = "oneshot";
      ExecStart = "${pkgs.bash}/bin/bash /etc/hypervisor/scripts/first_boot_welcome.sh";
      User = "root";
      WorkingDirectory = "/etc/hypervisor";
      NoNewPrivileges = true;
      PrivateTmp = true;
      ProtectSystem = "strict";
      ProtectHome = true;
      StateDirectory = "hypervisor";
      
      ExecStartPre = [
        "${pkgs.coreutils}/bin/mkdir -p /var/lib/hypervisor/logs"
        "${pkgs.coreutils}/bin/touch /var/lib/hypervisor/logs/first_boot.log"
      ];
      
      ReadWritePaths = [ 
        "/var/lib/hypervisor/logs" 
        "/var/lib/hypervisor/.first_boot_welcome_shown" 
      ];
      
      StandardInput = "tty";
      StandardOutput = "tty";
      TTYPath = "/dev/tty1";
      TTYReset = true;
      TTYVHangup = true;
      
      Environment = [ 
        "DIALOG=whiptail" 
        "TERM=linux" 
        "HOME=/root" 
        "PATH=/run/current-system/sw/bin:/usr/sbin:/usr/bin:/sbin:/bin" 
      ];
    };
    
    unitConfig.ConditionPathExists = "!/var/lib/hypervisor/.first_boot_welcome_shown";
  };
  
  # ═══════════════════════════════════════════════════════════════
  # Systemd Services - First Boot Wizard
  # ═══════════════════════════════════════════════════════════════
  systemd.services.hypervisor-first-boot = {
    description = "First-boot Setup Wizard (Disabled)";
    wantedBy = lib.optional config.hypervisor.firstBootWizard.enableAtBoot "multi-user.target";
    after = [ "network-online.target" "systemd-tmpfiles-setup.service" ];
    before = [ "hypervisor-menu.service" ];
    wants = [ "network-online.target" ];
    conflicts = [ "getty@tty1.service" ];
    
    serviceConfig = {
      Type = "oneshot";
      ExecStart = "${pkgs.bash}/bin/bash -c 'if [ ! -f /var/lib/hypervisor/.first_boot_done ]; then ${pkgs.bash}/bin/bash /etc/hypervisor/scripts/setup_wizard.sh || true; ${pkgs.coreutils}/bin/touch /var/lib/hypervisor/.first_boot_done; fi'";
      User = "root";
      WorkingDirectory = "/etc/hypervisor";
      NoNewPrivileges = true;
      PrivateTmp = true;
      ProtectSystem = "strict";
      ProtectHome = true;
      StateDirectory = "hypervisor";
      LogsDirectory = "";
      
      ExecStartPre = [
        "${pkgs.coreutils}/bin/mkdir -p /var/lib/hypervisor/logs"
        "${pkgs.coreutils}/bin/touch /var/lib/hypervisor/logs/first_boot.log"
        "${pkgs.coreutils}/bin/mkdir -p /etc/hypervisor/src/configuration"
      ];
      
      ReadWritePaths = [ 
        "/etc/hypervisor/src/configuration" 
        "/var/lib/hypervisor/logs" 
      ];
      
      StandardInput = "tty";
      StandardOutput = "tty";
      TTYPath = "/dev/tty1";
      TTYReset = true;
      TTYVHangup = true;
      
      Environment = [ 
        "DIALOG=whiptail" 
        "TERM=linux" 
        "HOME=/root" 
        "PATH=/run/current-system/sw/bin:/usr/sbin:/usr/bin:/sbin:/bin" 
      ];
    };
    
    unitConfig.ConditionPathExists = "!/var/lib/hypervisor/.first_boot_done";
  };
}
