# First Boot Configuration Service
# Runs the configuration wizard on first boot

{ config, lib, pkgs, ... }:

let
  inherit (lib) mkOption mkEnableOption mkIf mkDefault mkForce mkMerge types;
  cfg = config.hypervisor.firstBoot;
  
  # Create a proper script with dependencies
  firstBootScript = pkgs.writeScriptBin "first-boot-wizard" ''
    #!${pkgs.bash}/bin/bash
    # First Boot Configuration Wizard
    # This is a minimal version that ensures the system can be configured
    
    set -euo pipefail
    
    # Colors
    readonly RED='\033[0;31m'
    readonly GREEN='\033[0;32m'
    readonly YELLOW='\033[1;33m'
    readonly BLUE='\033[0;34m'
    readonly NC='\033[0m'
    
    # Configuration
    readonly CONFIG_FILE="/etc/nixos/configuration.nix"
    readonly FIRST_BOOT_FLAG="/var/lib/hypervisor/.first-boot-complete"
    
    echo -e "''${BLUE}═══════════════════════════════════════════════════════════════''${NC}"
    echo -e "''${BLUE}         Welcome to Hyper-NixOS First Boot Setup                ''${NC}"
    echo -e "''${BLUE}═══════════════════════════════════════════════════════════════''${NC}"
    echo
    echo -e "''${YELLOW}This wizard will help you configure your system.''${NC}"
    echo
    
    # Check if running as root
    if [[ $EUID -ne 0 ]]; then
        echo -e "''${RED}This script must be run as root!''${NC}"
        exit 1
    fi
    
    # Ensure we're on a TTY
    if ! tty -s; then
        echo -e "''${RED}This script must be run on a TTY!''${NC}"
        exit 1
    fi
    
    echo -e "''${GREEN}First, let's set up the admin user password.''${NC}"
    echo -e "''${YELLOW}The current admin user has a default password that must be changed.''${NC}"
    echo
    
    # Change admin password
    echo "Setting password for 'admin' user:"
    passwd admin || {
        echo -e "''${RED}Failed to set admin password!''${NC}"
        exit 1
    }
    
    echo
    echo -e "''${GREEN}✓ Admin password updated successfully!''${NC}"
    echo
    
    # Ask about system tier
    echo -e "''${BLUE}Select your system tier:''${NC}"
    echo "1) Minimal - Basic VM management (2GB RAM minimum)"
    echo "2) Standard - Common features (4GB RAM recommended)"
    echo "3) Enhanced - Advanced features (8GB RAM recommended)"
    echo "4) Professional - Full features (16GB RAM recommended)"
    echo "5) Enterprise - All features (32GB RAM recommended)"
    echo
    read -p "Enter choice [1-5]: " tier_choice
    
    case $tier_choice in
        1) tier="minimal" ;;
        2) tier="standard" ;;
        3) tier="enhanced" ;;
        4) tier="professional" ;;
        5) tier="enterprise" ;;
        *) tier="standard" ;;
    esac
    
    echo
    echo -e "''${GREEN}Selected tier: $tier''${NC}"
    echo
    
    # Create tier configuration
    cat > "$CONFIG_FILE.new" <<EOF
# Hyper-NixOS Configuration
# Generated by First Boot Wizard on $(date)
# Selected Tier: $tier

{ config, lib, pkgs, ... }:

{
  imports = [
    # Import the base configuration
    ./configuration-minimal.nix
    # Import the selected tier
    ./modules/system-tiers.nix
  ];
  
  # Set the selected tier
  hypervisor.systemTier = "$tier";
  
  # First boot is complete
  hypervisor.firstBoot.autoStart = false;
}
EOF
    
    # Backup original and apply new config
    cp "$CONFIG_FILE" "$CONFIG_FILE.backup-$(date +%Y%m%d-%H%M%S)"
    mv "$CONFIG_FILE.new" "$CONFIG_FILE"
    
    echo -e "''${GREEN}Configuration updated!''${NC}"
    echo
    echo "The system will now rebuild with your selected configuration."
    echo "This may take a few minutes..."
    echo
    
    # Rebuild the system
    nixos-rebuild switch || {
        echo -e "''${RED}System rebuild failed!''${NC}"
        echo "Restoring backup configuration..."
        cp "$CONFIG_FILE.backup-$(date +%Y%m%d-%H%M%S)" "$CONFIG_FILE"
        exit 1
    }
    
    # Mark first boot as complete
    mkdir -p "$(dirname "$FIRST_BOOT_FLAG")"
    touch "$FIRST_BOOT_FLAG"
    
    echo
    echo -e "''${GREEN}═══════════════════════════════════════════════════════════════''${NC}"
    echo -e "''${GREEN}        First boot configuration complete!                      ''${NC}"
    echo -e "''${GREEN}═══════════════════════════════════════════════════════════════''${NC}"
    echo
    echo "You can now log in with:"
    echo "  Username: admin"
    echo "  Password: (the password you just set)"
    echo
    echo "Press Enter to continue..."
    read -r
  '';
in
{
  options.hypervisor.firstBoot = {
    enable = mkOption {
      type = types.bool;
      default = true;
      description = "Enable first boot configuration wizard";
    };
    
    autoStart = mkOption {
      type = types.bool;
      default = true;
      description = "Automatically start wizard on first boot";
    };
  };
  
  config = mkIf cfg.enable {
    # Install the wizard script
    environment.systemPackages = [ firstBootScript ];
    
    # Ensure the hypervisor directory exists
    systemd.tmpfiles.rules = [
      "d /var/lib/hypervisor 0755 root root -"
    ];
    
    # Create systemd service for first boot
    systemd.services.hypervisor-first-boot = mkIf cfg.autoStart {
      description = "Hyper-NixOS First Boot Configuration Wizard";
      
      # Only run on first boot
      unitConfig = {
        ConditionPathExists = "!/var/lib/hypervisor/.first-boot-complete";
      };
      
      serviceConfig = {
        Type = "idle";  # Wait for other services to finish
        RemainAfterExit = true;
        StandardInput = "tty-force";
        StandardOutput = "inherit";
        StandardError = "inherit";
        TTYPath = "/dev/tty1";
        TTYReset = true;
        TTYVHangup = true;
        
        # Ensure directory exists before running
        ExecStartPre = "${pkgs.coreutils}/bin/mkdir -p /var/lib/hypervisor";
        
        # Run the wizard
        ExecStart = "${firstBootScript}/bin/first-boot-wizard";
        
        # Create completion flag
        ExecStartPost = "${pkgs.coreutils}/bin/touch /var/lib/hypervisor/.first-boot-complete";
      };
      
      # Run after basic system is up but before getty
      after = [ "sysinit.target" "basic.target" ];
      before = [ "getty.target" ];
      wantedBy = [ "multi-user.target" ];
      
      # Take over tty1 from getty
      conflicts = [ "getty@tty1.service" ];
    };
    
    # Override getty@tty1 to wait for first-boot if needed
    systemd.services."getty@tty1" = mkIf cfg.autoStart {
      overrideStrategy = "asDropin";
      unitConfig = {
        # Don't start getty@tty1 until first boot is complete
        ConditionPathExists = "/var/lib/hypervisor/.first-boot-complete";
      };
    };
    
    # Also provide a manual way to run the wizard
    environment.etc."hypervisor/bin/reconfigure-tier" = {
      mode = "0755";
      text = ''
        #!/usr/bin/env bash
        # Remove first boot flag and run wizard
        
        if [[ $EUID -ne 0 ]]; then
          echo "This script must be run as root"
          exit 1
        fi
        
        echo "This will reconfigure your system tier."
        read -p "Continue? (y/N): " confirm
        
        if [[ $confirm =~ ^[Yy]$ ]]; then
          rm -f /var/lib/hypervisor/.first-boot-complete
          ${firstBootScript}/bin/first-boot-wizard
        else
          echo "Cancelled."
        fi
      '';
    };
  };
}