name: Rust Tests

on:
  push:
    branches: [ main, develop, 'cursor/**' ]
    paths:
      - 'tools/**/*.rs'
      - 'tools/**/Cargo.toml'
      - '.github/workflows/rust-tests.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'tools/**/*.rs'
      - 'tools/**/Cargo.toml'

jobs:
  test:
    name: Rust Test and Lint
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          components: clippy, rustfmt
          override: true
      
      - name: Cache cargo registry
        uses: actions/cache@v3
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
      
      - name: Cache cargo index
        uses: actions/cache@v3
        with:
          path: ~/.cargo/git
          key: ${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}
      
      - name: Cache cargo build
        uses: actions/cache@v3
        with:
          path: tools/target
          key: ${{ runner.os }}-cargo-build-target-${{ hashFiles('**/Cargo.lock') }}
      
      - name: Run cargo fmt
        working-directory: tools
        run: cargo fmt --all -- --check
      
      - name: Run cargo clippy
        working-directory: tools
        run: cargo clippy --all-targets --all-features -- -D warnings
      
      - name: Run cargo test
        working-directory: tools
        run: cargo test --all --verbose
      
      - name: Build release binaries
        working-directory: tools
        run: cargo build --release --all
      
      - name: Test Summary
        if: always()
        run: |
          echo "### Rust Test Results 🦀" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Status:** ${{ job.status }}" >> $GITHUB_STEP_SUMMARY
