name: ShellCheck

on:
  push:
    branches: [ main, master, develop ]
    paths:
      - '**.sh'
      - '.github/workflows/shellcheck.yml'
  pull_request:
    branches: [ main, master, develop ]
    paths:
      - '**.sh'
      - '.github/workflows/shellcheck.yml'

jobs:
  shellcheck:
    name: ShellCheck
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Run ShellCheck
      uses: ludeeus/action-shellcheck@master
      with:
        scandir: './scripts'
        severity: warning
        check_together: 'yes'
        format: gcc
      env:
        SHELLCHECK_OPTS: -e SC2086 -e SC2059  # Exclude some common false positives if needed
    
    - name: Check additional shell files
      run: |
        # Find all shell scripts not in scripts/ directory
        find . -name "*.sh" -not -path "./scripts/*" -not -path "./.git/*" -type f -print0 | \
        xargs -0 -r shellcheck -f gcc -s bash || exit 1
    
    - name: Upload ShellCheck results
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: shellcheck-results
        path: shellcheck-results.txt
        retention-days: 7